#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario_2._1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Inventario")]
	public partial class InventarioDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertINVProducto(INVProducto instance);
    partial void UpdateINVProducto(INVProducto instance);
    partial void DeleteINVProducto(INVProducto instance);
    partial void InsertINVCategoria(INVCategoria instance);
    partial void UpdateINVCategoria(INVCategoria instance);
    partial void DeleteINVCategoria(INVCategoria instance);
    partial void InsertINVUM(INVUM instance);
    partial void UpdateINVUM(INVUM instance);
    partial void DeleteINVUM(INVUM instance);
    #endregion
		
		public InventarioDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["InventarioConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public InventarioDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InventarioDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InventarioDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InventarioDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<INVProducto> INVProducto
		{
			get
			{
				return this.GetTable<INVProducto>();
			}
		}
		
		public System.Data.Linq.Table<INVCategoria> INVCategoria
		{
			get
			{
				return this.GetTable<INVCategoria>();
			}
		}
		
		public System.Data.Linq.Table<INVUM> INVUM
		{
			get
			{
				return this.GetTable<INVUM>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.INVProducto")]
	public partial class INVProducto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ProductoId;
		
		private string _Codigo;
		
		private string _Nombre;
		
		private string _Abreviatura;
		
		private int _CategoriaID;
		
		private int _UMID;
		
		private decimal _Costo;
		
		private decimal _Precio;
		
		private bool _EsInventariado;
		
		private bool _EsParaVenta;
		
		private byte[] _Imagen;
		
		private byte _Estado;
		
		private System.DateTime _FechaCreacion;
		
		private System.DateTime _FechaModificacion;
		
		private EntityRef<INVCategoria> _INVCategoria;
		
		private EntityRef<INVUM> _INVUM;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductoIDChanging(long value);
    partial void OnProductoIDChanged();
    partial void OnCodigoChanging(string value);
    partial void OnCodigoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnAbreviaturaChanging(string value);
    partial void OnAbreviaturaChanged();
    partial void OnCategoriaIDChanging(int value);
    partial void OnCategoriaIDChanged();
    partial void OnUMIDChanging(int value);
    partial void OnUMIDChanged();
    partial void OnCostoChanging(decimal value);
    partial void OnCostoChanged();
    partial void OnPrecioChanging(decimal value);
    partial void OnPrecioChanged();
    partial void OnEsInventariadoChanging(bool value);
    partial void OnEsInventariadoChanged();
    partial void OnEsParaVentaChanging(bool value);
    partial void OnEsParaVentaChanged();
    partial void OnImagenChanging(byte[] value);
    partial void OnImagenChanged();
    partial void OnEstadoChanging(byte value);
    partial void OnEstadoChanged();
    partial void OnFechaCreacionChanging(System.DateTime value);
    partial void OnFechaCreacionChanged();
    partial void OnFechaModificacionChanging(System.DateTime value);
    partial void OnFechaModificacionChanged();
    #endregion
		
		public INVProducto()
		{
			this._INVCategoria = default(EntityRef<INVCategoria>);
			this._INVUM = default(EntityRef<INVUM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ProductoId", Storage="_ProductoId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ProductoID
		{
			get
			{
				return this._ProductoId;
			}
			set
			{
				if ((this._ProductoId != value))
				{
					this.OnProductoIDChanging(value);
					this.SendPropertyChanging();
					this._ProductoId = value;
					this.SendPropertyChanged("ProductoID");
					this.OnProductoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abreviatura", DbType="NVarChar(3) NOT NULL", CanBeNull=false)]
		public string Abreviatura
		{
			get
			{
				return this._Abreviatura;
			}
			set
			{
				if ((this._Abreviatura != value))
				{
					this.OnAbreviaturaChanging(value);
					this.SendPropertyChanging();
					this._Abreviatura = value;
					this.SendPropertyChanged("Abreviatura");
					this.OnAbreviaturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaID", DbType="Int NOT NULL")]
		public int CategoriaID
		{
			get
			{
				return this._CategoriaID;
			}
			set
			{
				if ((this._CategoriaID != value))
				{
					if (this._INVCategoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCategoriaIDChanging(value);
					this.SendPropertyChanging();
					this._CategoriaID = value;
					this.SendPropertyChanged("CategoriaID");
					this.OnCategoriaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UMID", DbType="Int NOT NULL")]
		public int UMID
		{
			get
			{
				return this._UMID;
			}
			set
			{
				if ((this._UMID != value))
				{
					if (this._INVUM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUMIDChanging(value);
					this.SendPropertyChanging();
					this._UMID = value;
					this.SendPropertyChanged("UMID");
					this.OnUMIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Costo", DbType="Decimal(15,5) NOT NULL")]
		public decimal Costo
		{
			get
			{
				return this._Costo;
			}
			set
			{
				if ((this._Costo != value))
				{
					this.OnCostoChanging(value);
					this.SendPropertyChanging();
					this._Costo = value;
					this.SendPropertyChanged("Costo");
					this.OnCostoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Decimal(15,5) NOT NULL")]
		public decimal Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this.OnPrecioChanging(value);
					this.SendPropertyChanging();
					this._Precio = value;
					this.SendPropertyChanged("Precio");
					this.OnPrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EsInventariado", DbType="Bit NOT NULL")]
		public bool EsInventariado
		{
			get
			{
				return this._EsInventariado;
			}
			set
			{
				if ((this._EsInventariado != value))
				{
					this.OnEsInventariadoChanging(value);
					this.SendPropertyChanging();
					this._EsInventariado = value;
					this.SendPropertyChanged("EsInventariado");
					this.OnEsInventariadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EsParaVenta", DbType="Bit NOT NULL")]
		public bool EsParaVenta
		{
			get
			{
				return this._EsParaVenta;
			}
			set
			{
				if ((this._EsParaVenta != value))
				{
					this.OnEsParaVentaChanging(value);
					this.SendPropertyChanging();
					this._EsParaVenta = value;
					this.SendPropertyChanged("EsParaVenta");
					this.OnEsParaVentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imagen", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public byte[] Imagen
		{
			get
			{
				return this._Imagen;
			}
			set
			{
				if ((this._Imagen != value))
				{
					this.OnImagenChanging(value);
					this.SendPropertyChanging();
					this._Imagen = value;
					this.SendPropertyChanged("Imagen");
					this.OnImagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="TinyInt NOT NULL")]
		public byte Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModificacion", DbType="DateTime NOT NULL")]
		public System.DateTime FechaModificacion
		{
			get
			{
				return this._FechaModificacion;
			}
			set
			{
				if ((this._FechaModificacion != value))
				{
					this.OnFechaModificacionChanging(value);
					this.SendPropertyChanging();
					this._FechaModificacion = value;
					this.SendPropertyChanged("FechaModificacion");
					this.OnFechaModificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="INVCategoria_INVProducto", Storage="_INVCategoria", ThisKey="CategoriaID", OtherKey="CategoriaID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public INVCategoria INVCategoria
		{
			get
			{
				return this._INVCategoria.Entity;
			}
			set
			{
				INVCategoria previousValue = this._INVCategoria.Entity;
				if (((previousValue != value) 
							|| (this._INVCategoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._INVCategoria.Entity = null;
						previousValue.INVProducto.Remove(this);
					}
					this._INVCategoria.Entity = value;
					if ((value != null))
					{
						value.INVProducto.Add(this);
						this._CategoriaID = value.CategoriaID;
					}
					else
					{
						this._CategoriaID = default(int);
					}
					this.SendPropertyChanged("INVCategoria");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="INVUM_INVProducto", Storage="_INVUM", ThisKey="UMID", OtherKey="UMID", IsForeignKey=true)]
		public INVUM INVUM
		{
			get
			{
				return this._INVUM.Entity;
			}
			set
			{
				INVUM previousValue = this._INVUM.Entity;
				if (((previousValue != value) 
							|| (this._INVUM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._INVUM.Entity = null;
						previousValue.INVProducto.Remove(this);
					}
					this._INVUM.Entity = value;
					if ((value != null))
					{
						value.INVProducto.Add(this);
						this._UMID = value.UMID;
					}
					else
					{
						this._UMID = default(int);
					}
					this.SendPropertyChanged("INVUM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.INVCategoria")]
	public partial class INVCategoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CategoriaID;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		private byte[] _Imagen;
		
		private byte _Estado;
		
		private System.DateTime _FechaCreacion;
		
		private System.DateTime _FechaModificacion;
		
		private EntitySet<INVProducto> _INVProducto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCategoriaIDChanging(int value);
    partial void OnCategoriaIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnImagenChanging(byte[] value);
    partial void OnImagenChanged();
    partial void OnEstadoChanging(byte value);
    partial void OnEstadoChanged();
    partial void OnFechaCreacionChanging(System.DateTime value);
    partial void OnFechaCreacionChanged();
    partial void OnFechaModificacionChanging(System.DateTime value);
    partial void OnFechaModificacionChanged();
    #endregion
		
		public INVCategoria()
		{
			this._INVProducto = new EntitySet<INVProducto>(new Action<INVProducto>(this.attach_INVProducto), new Action<INVProducto>(this.detach_INVProducto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CategoriaID
		{
			get
			{
				return this._CategoriaID;
			}
			set
			{
				if ((this._CategoriaID != value))
				{
					this.OnCategoriaIDChanging(value);
					this.SendPropertyChanging();
					this._CategoriaID = value;
					this.SendPropertyChanged("CategoriaID");
					this.OnCategoriaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imagen", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public byte[] Imagen
		{
			get
			{
				return this._Imagen;
			}
			set
			{
				if ((this._Imagen != value))
				{
					this.OnImagenChanging(value);
					this.SendPropertyChanging();
					this._Imagen = value;
					this.SendPropertyChanged("Imagen");
					this.OnImagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="TinyInt NOT NULL")]
		public byte Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModificacion", DbType="DateTime NOT NULL")]
		public System.DateTime FechaModificacion
		{
			get
			{
				return this._FechaModificacion;
			}
			set
			{
				if ((this._FechaModificacion != value))
				{
					this.OnFechaModificacionChanging(value);
					this.SendPropertyChanging();
					this._FechaModificacion = value;
					this.SendPropertyChanged("FechaModificacion");
					this.OnFechaModificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="INVCategoria_INVProducto", Storage="_INVProducto", ThisKey="CategoriaID", OtherKey="CategoriaID")]
		public EntitySet<INVProducto> INVProducto
		{
			get
			{
				return this._INVProducto;
			}
			set
			{
				this._INVProducto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_INVProducto(INVProducto entity)
		{
			this.SendPropertyChanging();
			entity.INVCategoria = this;
		}
		
		private void detach_INVProducto(INVProducto entity)
		{
			this.SendPropertyChanging();
			entity.INVCategoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.INVUM")]
	public partial class INVUM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UMID;
		
		private string _Nombre;
		
		private string _Abrev;
		
		private byte _Estado;
		
		private System.DateTime _FechaCreacion;
		
		private System.DateTime _FechaModificacion;
		
		private EntitySet<INVProducto> _INVProducto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUMIDChanging(int value);
    partial void OnUMIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnAbrevChanging(string value);
    partial void OnAbrevChanged();
    partial void OnEstadoChanging(byte value);
    partial void OnEstadoChanged();
    partial void OnFechaCreacionChanging(System.DateTime value);
    partial void OnFechaCreacionChanged();
    partial void OnFechaModificacionChanging(System.DateTime value);
    partial void OnFechaModificacionChanged();
    #endregion
		
		public INVUM()
		{
			this._INVProducto = new EntitySet<INVProducto>(new Action<INVProducto>(this.attach_INVProducto), new Action<INVProducto>(this.detach_INVProducto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UMID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UMID
		{
			get
			{
				return this._UMID;
			}
			set
			{
				if ((this._UMID != value))
				{
					this.OnUMIDChanging(value);
					this.SendPropertyChanging();
					this._UMID = value;
					this.SendPropertyChanged("UMID");
					this.OnUMIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abrev", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Abrev
		{
			get
			{
				return this._Abrev;
			}
			set
			{
				if ((this._Abrev != value))
				{
					this.OnAbrevChanging(value);
					this.SendPropertyChanging();
					this._Abrev = value;
					this.SendPropertyChanged("Abrev");
					this.OnAbrevChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="TinyInt NOT NULL")]
		public byte Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModificacion", DbType="DateTime NOT NULL")]
		public System.DateTime FechaModificacion
		{
			get
			{
				return this._FechaModificacion;
			}
			set
			{
				if ((this._FechaModificacion != value))
				{
					this.OnFechaModificacionChanging(value);
					this.SendPropertyChanging();
					this._FechaModificacion = value;
					this.SendPropertyChanged("FechaModificacion");
					this.OnFechaModificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="INVUM_INVProducto", Storage="_INVProducto", ThisKey="UMID", OtherKey="UMID")]
		public EntitySet<INVProducto> INVProducto
		{
			get
			{
				return this._INVProducto;
			}
			set
			{
				this._INVProducto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_INVProducto(INVProducto entity)
		{
			this.SendPropertyChanging();
			entity.INVUM = this;
		}
		
		private void detach_INVProducto(INVProducto entity)
		{
			this.SendPropertyChanging();
			entity.INVUM = null;
		}
	}
}
#pragma warning restore 1591
